### ISSUE TITLE
Sending Action causes JSONDecodeError 

### ISSUE THREAD

**Issue by williamschey** [Omlet-Ltd/smartcoop-python-sdk#1]
Hi,

Thanks for the SDK, it is amazing to see companies providing this stuff out of the box. Started creating a Home Assistant integration, https://github.com/williamschey/hassio-omlet-smartcoop-door and found an issue with the SDK.

When one uses the perform_action it causes a decode error. Seems it is due to the PUT request not providing back any data and providing a 204 (which is correct). See below:

https://stackoverflow.com/questions/16573332/jsondecodeerror-expecting-value-line-1-column-1-char-0

This occurs on both HASS and Fedora 41 (Python ver. Python 3.13.0)

```
from smartcoop.client import SmartCoopClient
from smartcoop.api.omlet import Omlet
try:
    api_key = '<SOME API KEY>'
    client = SmartCoopClient(client_secret=api_key)
    api = Omlet(client)
    mydevice = api.get_device_by_id('<SOME DEVICE ID>')
    omlet_action = next((action for action in mydevice.actions if action.name == 'open'), None)
    api.perform_action(omlet_action)
    print("The code should be able to get here BUT does not!")
except Exception as ex:
    print(ex)
```

results in

```
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/lib64/python3.13/json/decoder.py", line 344, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/json/decoder.py", line 362, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/scheyw/Code/omlet_test/test.py", line 11, in <module>
    api.perform_action(omlet_action)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/scheyw/.local/lib/python3.13/site-packages/smartcoop/api/omlet.py", line 23, in perform_action
    self.client.post(endpoint)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/scheyw/.local/lib/python3.13/site-packages/smartcoop/client.py", line 26, in post
    return response.json()
           ~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by williamschey** [comment]
See PR for fix
